### PR TITLE
added two new images for expeditionary robotics project

### PR DESCRIPTION
**Pull request by bvundurthy**

### CODE REVIEW

**Comment by gnastacast** [comment]
Are these images on a page somewhere? I don't see an actual post you added.

**Comment by bvundurthy** [comment]
Hi Nico,

I've been trying to add the pages but I am getting a timed-out error since yesterday. I pinged you on slack to see if we could find some time to fix it.

Let me know if you are up for a small chat.

Best regards,
Bhaskar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gnastacast** [comment]
What's the name of the page?

**Comment by bvundurthy** [comment]
There is no page right now since it is not even saving.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bvundurthy** [comment]
Hi Nico,

Here is a link to the sheet I created and wanted to make three pages for the three projects:
https://docs.google.com/document/d/1JMQ-szw9QanAZ9PdP_2wSLE_B6vORIqrC7Uvo0Y0VxU/edit?usp=sharing


Best regards,
Bhaskar
________________________________

**Pull request merged**
